#!/bin/bash
# WARNING: this script will destroy data on the selected disk.
# This script can be run by executing the following:
#   curl -sL https://git.io/vAoV8 | bash
set -uo pipefail
trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR

### Set up pacman ###
REPO_URL="https://liam-repo.s3.eu-west-2.amazonaws.com/x86_x64/"
MIRRORLIST_URL="https://www.archlinux.org/mirrorlist/?country=GB&protocol=https&use_mirror_status=on"

pacman -Sy --noconfirm pacman-contrib dialog

echo "Updating mirror list"
curl -s "$MIRRORLIST_URL" | \
    sed -e 's/^#Server/Server/' -e '/^#/d' | \
    rankmirrors -n 5 - > /etc/pacman.d/mirrorlist

### Get variable info from user ###
hostname=$(dialog --stdout --inputbox "Enter hostname" 0 0) || exit 1
clear
: ${hostname:?"hostname cannot be empty"}

user=$(dialog --stdout --inputbox "Enter username" 0 0) || exit 1
clear
: ${user:?"user cannot be empty"}

password=$(dialog --stdout --passwordbox "Enter admin password" 0 0) || exit 1
clear
: ${password:?"password cannot be empty"}
password2=$(dialog --stdout --passwordbox "Enter admin password again" 0 0) || exit 1
clear
[[ "$password" == "$password2" ]] || ( echo "Passwords did not match"; exit 1; )

uefi=$(dialog --stdout --inputbox "Enter uefi partition" 0 0) || exit 1
clear
: ${uefi:?"uefi partition cannot be empty"}

root=$(dialog --stdout --inputbox "Enter root partition" 0 0) || exit 1
clear
: ${root:?"root partition cannot be empty"}

installing=$(dialog --stdout --inputbox "Enter packages to install" 0 0) || exit 1
clear
: ${installing:?"Installation info cannot be empty"}

### Set up logging ###
exec 1> >(tee "stdout.log")
exec 2> >(tee "stderr.log")

### NTP and keyboard setup ###
timedatectl set-ntp true
loadkeys uk

### Mount partitions ###
mount "${root}" /mnt
mkdir /mnt/boot
mount "${uefi}" /mnt/boot

### Install and configure the basic system ###
cat >>/etc/pacman.conf <<EOF
[multilib]
Include = /etc/pacman.d/mirrorlist

[liam]
SigLevel = Optional TrustAll
Server = $REPO_URL
EOF

pacstrap /mnt "{$installing}" 

genfstab -t PARTUUID /mnt >> /mnt/etc/fstab
echo "${hostname}" > /mnt/etc/hostname

cat <<EOF > /etc/hosts
127.0.0.1       localhost
::1             localhost
127.0.1.1       $hostname.localdomain $hostname
EOF

cat >>/mnt/etc/pacman.conf <<EOF
[multilib]
Include = /etc/pacman.d/mirrorlist

[liam]
SigLevel = Optional TrustAll
Server = $REPO_URL
EOF

### Bootloader ##
arch-chroot /mnt refind-install efibootmgr

### Add user ###
arch-chroot /mnt useradd -mU -s /usr/bin/zsh -G wheel,uucp,video,audio,storage,games,input "$user"
arch-chroot /mnt chsh -s /usr/bin/zsh

echo "$user:$password" | chpasswd --root /mnt
echo "root:$password" | chpasswd --root /mnt


