#!/bin/bash
#
#
#

set -uo pipefail
trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR

REPO_URL="https://s3.eu-west-2.amazonaws.com/mdaffin-arch/repo/x86_64"
MIRRORLIST_URL="https://www.archlinux.org/mirrorlist/?country=GB&protocol=https&use_mirror_status=on"

### Info needed

hostname=$(dialog --stdout --inputbox "Enter hostname" 0 0) || exit 1
clear
: ${hostname:?"hostname cannot be empty"}

### Mirrors
#pacman -Sy --noconfirm pacman-contrib dialog
#echo "Updating mirror list"
#curl -s "$MIRRORLIST_URL" | \
#    sed -e 's/^#Server/Server/' -e '/^#/d' | \
#    rankmirrors -n 5 - > /etc/pacman.d/mirrorlist

### Install system
#pacstrap /mnt liam-laptop

### Fstab
#genfstab -U /mnt >> /mnt/etc/fstab


