#!/bin/bash
#
# First time - need to change pacman.conf, upload database, then do the rest

#mkdir -p /home/liam/arch_install/local-repo

#repo-add /home/liam/arch_install/local-repo/liam-repo.db.tar.xz

#aur sync --repo liam-repo --root /home/liam/arch_install/local-repo aurutils google-chrome optimus-manager 

#aur sync --repo liam-repo --root /home/liam/arch_install/local-repo -u

repo-add /home/liam/arch_install/local-repo/liam-repo.db.tar.xz /home/liam/arch_install/liam-desktop/liam-desktop-1-1-any.pkg.tar.zst

s3cmd sync --follow-symlinks --acl-public /home/liam/arch_install/liam-desktop/liam-desktop-1-1-any.pkg.tar.zst s3://liam-repo/repo/

#s3cmd sync --follow-symlinks --acl-public /home/liam/arch_install/local-repo/ s3://liam-repo/repo/

s3cmd sync --follow-symlinks --acl-public /home/liam/arch_install/local-repo/liam-repo.{db,files}{,.tar.xz} s3://liam-repo/repo/

